---
title: " "
project:
  output-dir: docs
format:
  html:
    toc: true
    toc-location: right
    embed-resources: true
editor: source

---

# **Datenschutzinformation für die Nutzung der App GESIS SMART**

Nachfolgend werden Informationen zum Datenschutz für die Nutzung der App GESIS SMART (im Folgenden „App“) erteilt.

## **Ziel und Umfang der GESIS-App**

GESIS – Leibniz-Institut für Sozialwissenschaften e.V. (im Folgenden „GESIS“) stellt dem Nutzer eine mobile App zur Verfügung, die er auf sein mobiles Gerät herunterladen kann. Durch Nutzung der App kann der Nutzer an wissenschaftlichen Studien teilnehmen.

Wissenschaftliche Forscher (im Folgenden „Forscher“) können mit dieser App Fragebögen an den Nutzer der App als Studienteilnehmer versenden. Die Forscher sind für die Datenerhebung innerhalb ihrer Studien allein verantwortlich, während GESIS die Daten im Auftrag der Forscher verarbeitet. Nach der Installation der App und dem Einloggen in die App mit einem Teilnahmecode wird der Nutzer durch die Forschenden über die spezifischen Ziele der jeweiligen Studie und die relevanten Datenschutzbestimmungen informiert. 

Der Forscher verpflichtet sich gegenüber GESIS zur Einhaltung der datenschutzrechtlichen Bestimmungen. Er beachtet insbesondere die Bestimmungen der Datenschutzgrundverordnung und des Bundesdatenschutzgesetzes. Der Forscher holt z.B. die Einwilligung von dem Nutzer als Studienteilnehmer für die Teilnahme an der Studie ein und informiert den Nutzer über die Verarbeitung seiner personenbezogenen Daten gemäß den gesetzlichen Bestimmungen. Zwischen dem Forscher und GESIS wird ein Auftragsverarbeitungsvertrag geschlossen. Der Forscher tritt als Verantwortlicher i.S.d. Art. 4 Nr. 7 DSGVO, GESIS als Auftragsverarbeiterin i.S.d. Art. 4 Nr. 8 DSGVO auf.

## **Durch Forscher stattfindende Verarbeitung personenbezogener Daten bei der Nutzung der App**

Die App ermöglicht es Forschern, Umfragen zu versenden und die Antworten des Nutzers zu wissenschaftlichen Zwecken zu verarbeiten. Nachdem der Nutzer die App auf seinem mobilen Gerät installiert und sich in einem spezifischen Studienprojekt angemeldet hat, erhält der Nutzer über die App zugesandte Fragebögen. Je nach Fragetyp wird der Nutzer aufgefordert, eine vordefinierte Antwort zu wählen, freien Text einzugeben oder Bilder hochzuladen. Der Forscher informiert den Nutzer über die genauen personenbezogenen Daten, die nach der Einwilligung des Nutzers im Rahmen der Studie erhoben werden. Personenbezogene Daten sind alle Daten, die mit Ihnen persönlich in Verbindung gebracht werden können, z. B. Name oder E-Mail-Adressen, eingegebene Antworten auf persönliche Fragen, Nutzer-ID. Die Rechtsgrundlage für die Verarbeitung der personenbezogenen Daten des Nutzers durch den Forscher ist Art. 6 Abs. 1 lit. a DSGVO und ggf. Art. 9 Abs. 2 lit. A DSGVO (Einwilligung). GESIS verarbeitet die personenbezogenen Daten im Auftrag des Forschers (Auftragsverarbeitung). Der Forscher ist Verantwortlicher i.S.d. Art. 4 Nr. 7 DSGVO.

## **Durch GESIS stattfindende Datenverarbeitung bei der Nutzung der App**

GESIS verarbeitet Informationen über den Gerätetyp (Hersteller) und die Version des Betriebssystems des vom Nutzer verwendeten mobilen Geräts, um die Funktionalität der App zu gewährleisten. Zum Zweck der Fehlerbehebung verarbeitet GESIS Metadaten zu den Umfrageantworten (z.B. Anzahl, Datum und Uhrzeit der Antworten) des Nutzers. Rechtsgrundlage der Verarbeitung ist Art. 6 Abs. 1 lit. b DSGVO, die Erfüllung des mit dem Nutzer geschlossenen Vertrags zur Nutzung der App.

Die App nutzt zur Versendung von Nachrichten die Anwendung Firebase Cloud Messaging. Sofern der Nutzer der Nutzung zustimmt, setzt das Unternehmen Google, die den in Android integrierten Push-Dienst Firebase Cloud Messaging betreibt, nach seiner ausdrücklichen Einwilligung Firebase Installations-IDs ein, um zu bestimmen, an welche Geräte Nachrichten gesendet werden sollen. Die Datenübermittlung erfolgt nur auf Grundlage, der durch den Nutzer ausdrücklich erklärten Einwilligung.

Die Informationen über den Gerätetyp, die Version des Betriebssystems des vom Nutzer verwendeten mobilen Geräts sowie die Metadaten zu den Umfrageantworten werden für die Dauer der Vertragsbeziehung mit dem Nutzer und für einen Zeitraum von 12 Monaten nach Vertragsbeendigung gespeichert. 

Verantwortlich für diese Datenverarbeitung ist: <br>

GESIS - Leibniz-Institut für Sozialwissenschaften e.V. <br>
B6, 4-5 <br>
68159 Mannheim <br>
Postfach 122155 <br>
68072 Mannheim <br>

Datenschutzbeauftragte von GESIS – Leibniz-Institut für Sozialwissenschaften e.V. ist: <br>

  HEC Harald Eul Consulting GmbH <br>
  Datenschutzbeauftragte GESIS <br>
  Auf der Höhe 34 <br>
  50321 Brühl <br>
  E-Mail: [Datenschutz-GESIS@he-c.de](Datenschutz-GESIS@he-c.de) <br>

Eine Weitergabe von personenbezogenen Daten durch GESIS ohne ausdrückliche Zustimmung des Nutzers ist ausgeschlossen. Der Nutzer hat in Bezug auf seine durch GESIS verarbeiteten Daten folgende Rechte:

  -	Auskunftsrecht, Art. 15 DSGVO
  -	Recht auf Berichtigung, Art. 16 DSGVO 
  -	Recht auf Löschung („Recht auf Vergessenwerden“), Art. 17 DSGVO
  -	Recht auf Einschränkung der Verarbeitung, Art. 18 DSGVO
  -	Recht auf Datenübertragbarkeit, Art. 20 DSGVO
  -	Widerspruchsrecht, Art. 21 DSGVO

Der Nutzer kann seine Rechte bei der Datenschutzbeauftragten von GESIS unter den oben genannten Kontaktdaten geltend machen.
Ferner steht dem Nutzer ein Beschwerderecht bei einer Aufsichtsbehörde zu (Art. 77 DSGVO). GESIS empfiehlt allerdings, eine Beschwerde zunächst immer an die Datenschutzbeauftragte von GESIS zu richten.
Sollten der Nutzer Fragen zum Datenschutz haben, wird er Nutzer gebeten, sich an die Datenschutzbeauftragte von GESIS unter den oben genannten Kontaktdaten zu wenden.

Durch die Weiterentwicklung der App oder aufgrund geänderter gesetzlicher bzw. behördlicher Vorgaben kann es notwendig werden, diese Datenschutzinformationen zu ändern. Der Nutzer kann die jeweils aktuellen Datenschutzinformationen jederzeit über die entsprechende Schaltfläche in der App abrufen.

Weitere Informationen zum Datenschutz sind unter [https://www.gesis.org/institut/datenschutz](https://www.gesis.org/institut/datenschutz) zu finden.



